---
title: "Data Organization & Cleaning File for _Probing connections between social connectedness, mortality risk, and brain age: A preregistered study_"
date: "March 1st, 2024"
authors: REDACTED
output: pdf_document
---

This data cleaning file gives rise to different versions of dataset: full MIDUS (Dataset A: Complete Observations N = 8,692), imputed imaging (Dataset B: N = 201), and raw/non-imputed imaging (Dataset C: N = 197). Descriptive statistics use non-imputed data (i.e, Dataset C; N = 197).

```{r libraries, eval = TRUE, message= FALSE, warning = FALSE, include = FALSE}
library(tidyverse)
library(naniar) # used to replace values w NA
library(psych)
library(GPArotation)
library(VIM)
library(ggplot2)
library(haven)
library(gt)
library(gtsummary)
library(dplyr)
library(mice) #imputation
library(MASS)
library(ggplot2)
library(pscl)
library(broom)
library(performance)
library(see)
library(patchwork)
library(rempsyc)
```

```{r read in raw data, eval = TRUE, message= FALSE, warning = FALSE, include = FALSE}
fulldataset <- read.csv("PATHNAME_REDACTED")

quality <- read.csv("PATHNAME_REDACTED")

brainage <- read.csv("PATHNAME_REDACTED")

mriIDs <- read.csv("PATHNAME_REDACTED")

refreshermort <- read_spss("PATHNAME_REDACTED")
```

```{r add mortality, eval = FALSE, include = FALSE}
refreshermort<- refreshermort %>% 
  rename(
    MIDUSID = MRID,
    ) %>% 
  dplyr::select(MIDUSID, DECEASED)

fulldataset <- left_join(fulldataset, refreshermort, by = c("MIDUSID"))
```

# Data Preparation and Cleaning

```{r Clean and rename data, eval = TRUE, include = FALSE}
#M2K is Midus Core Milwaukee
#MRK is Midus Refresher Milwaukee

#cleandata <- fulldata %>% 
cleanfulldataset <- fulldataset %>% 
  replace_with_na(replace = list(B1SPWBR1 = c(-1.0,98),
                                 B1SPWBR2 = c(-1.0, -1.00000, 98), 
                                 #RA1SPWBR1 = c(-1.0, 98.0), #didn't pull this from data but not needed
                                 RA1SPWBR2 = c(-1.0, -1.00000, 98.0),
                                 CASPWBR2 = c(-1.0, -1.00000, 98.0),
                                 B1SMADL = c(-1.0, 8.0),
                                 RA1SIADL = c(-1.0, 8.0),
                                 B1SBADL1 = c(-1.0, 8.0), 
                                 RA1SBADL1 = c(-1.0, 8.0), 
                                 B1SBADL2 = c(-1.0, 8.0), 
                                 RA1SBADL2 = c(-1.0, 8.0),
                                 A1SE9 = c(-1, 98, 99),
                                 RA1SD9 = c(-1, 8),
                                 A1PC14 = c(-1, 8, 9), 
                                 RA1PB53 = c(8),
                                 B4PBMI = c(998),
                                 B1PB1 = c(97, 98, 99), 
                                 RA1PB1 = c(97,98), 
                                 B1PF1 = c(97, 98, 99), 
                                 RA1PF1 = c(97, 98),
                                 A1SS7R = c(7,8,9),
                                 B1PF8_A = c(8, 9),
                                 RA1PF8A1 = c(8, 9), 
                                 B1PF7A = c(8, 9, NA),
                                 B1PF8B = c(8,9, NA),
                                 RA1PF7A= c(8, 9, NA),  
                                 RA1PF8B = c(8,9),
                                 B1STINC1 = c(-1,9999998),
                                 RA1STINC = c(-1, 999998),
                                 CACTINC = c(999998),
                                 RAACTINC = c(999998),
                                 CACF7A = c(8, 9, NA),
                                 RAACF7A = c(8, 9, NA),
                                 CACF8AX = c(8, 9),
                                 RAACF8AX = c(8, 9),
                                 CACF1 = c(97, 98),
                                 RAACF1 = c(97, 98),
                                 CACB1 = c(97,98),
                                 RAACB1 = c(97,98),
                                 RAACCA14 = c(7,8),
                                 RAACEA9 = c(97,98))) %>% 
  rename(M2P1_Age = B1PRAGE_2019, # age at behavioral assessment for M2 cohort
         M2P5_Age = B5PAGE, # age at imaging assessment for M2 cohort
         M2KP1_Age = CACRAGE, # age at behavioral assessment for M2 Milwaukee cohort
         MRP1_Age = RA1PRAGE, # age at behavioral assessment for MR cohort
         MRKP1_Age = RAACRAGE, # age at behavioral assessment for MR Milwaukee cohort
         MRP5_Age = RA5PAGE, # # age at imaging assessment for MR cohort
         M2P5_Sex = B1PRSEX, # M2 sex 
         MRP5_Sex = RA1PRSEX, # MR sex 
         M2P1_education = B1PB1, 
         M2KP1_education = CACB1,
         MRP1_education = RA1PB1, 
         MRKP1_education = RAACB1,
         M2P1_latine = B1PF1,
         M2KP1_latine = CACF1,
         MRP1_latine = RA1PF1,
         MRKP1_latine = RAACF1,
         M2P1_race1 = B1PF7A,
         M2P1_race2 = B1PF8B,
         M2P1_racebest = B1PF8_A,
         M2KP1_race1 = CACF7A,
         M2KP1_racebest = CACF8AX,
         M1P1_race = A1SS7R,
         MRP1_race1 = RA1PF7A,
         MRP1_race2 = RA1PF8B,
         MRP1_racebest = RA1PF8A1,
         MRKP1_race1 = RAACF7A,
         MRKP1_racebest = RAACF8AX,
         M2P1_income = B1STINC1,
         M2KP1_income = CACTINC, 
         MRP1_income = RA1STINC,
         MRKP1_income = RAACTINC, 
         M1P1_childhoodfinances = A1SE9,
         M1P1_childhoodwelfare = A1PC14,
         MRP1_childhoodfinances= RA1SD9,
         MRP1_childhoodwelfare = RA1PB53,
         MRKP1_childhoodfinances= RAACEA9,
         MRKP1_childhoodwelfare = RAACCA14,
         M2P4_BMI = B4PBMI,
         MRP4_BMI = RA4PBMI,
         M2P1_Panic = B1PPANDX,
         M2P1_Depression = B1PDEPDX,
         M2P1_Anxiety = B1PANXTD,
         M2KP1_Panic = CACPANDX,
         M2KP1_Depression = CACDEPDX,
         M2KP1_Anxiety = CACANXTD,
         MRP1_Panic = RA1PPANDX,
         MRP1_Depression = RA1PDEPDX,
         MRP1_Anxiety = RA1PANXTD,
         MRKP1_Panic = RAACPANDX,
         MRKP1_Depression = RAACDEPDX,
         MRKP1_Anxiety = RAACANXTD,
         M2P1_pos_relations_others3 = B1SPWBR1, 
         M2P1_pos_relations_others7 = B1SPWBR2, 
         M2KP1_pos_relations_others7 = CASPWBR2, 
         #MRP1_pos_relations_others3 = RA1SPWBR1, didn't pull this out, but not needed
         MRP1_pos_relations_others7 = RA1SPWBR2, 
         MRKP1_pos_relations_others7 = RAASPWBR2, 
         M2P4_TotalChronicConditions = B4HSYMN, 
         MRP4_TotalChronicConditions = RA4HSYMN,  
         M2P1_IADL = B1SMADL,
         M2P1_BasicADL2 = B1SBADL1, 
         M2P1_BasicADL3 = B1SBADL2, 
         M2KP1_IADL = CACIADL,      
         M2KP1_BasicADL3 = CACBADL2, 
         MRP1_IADL = RA1SIADL,
         MRP1_BasicADL2 = RA1SBADL1, 
         MRP1_BasicADL3 = RA1SBADL2,
         MRKP1_IADL = RAACIADL,
         MRKP1_BasicADL3 = RAACBADL2, 
         #DeathStatus = DECEASED
         )
```

```{r reshape data, eval = TRUE, include = FALSE}
cleanfulldataset <- cleanfulldataset %>%
  unite("FirstAge", c(M2P1_Age, MRP1_Age, M2KP1_Age, MRKP1_Age), sep = "", na.rm = TRUE) %>% 
  unite("ScanAge", M2P5_Age, MRP5_Age, sep = "", na.rm = TRUE) %>% 
  unite("Sex", M2P5_Sex, MRP5_Sex, sep = "", na.rm = TRUE) %>% 
  unite("PanicDx", c(M2P1_Panic, MRP1_Panic,M2KP1_Panic, MRKP1_Panic), sep = "", na.rm = TRUE) %>% 
  unite("DepressionDx", c(M2P1_Depression, MRP1_Depression, M2KP1_Depression, MRKP1_Depression), sep = "", na.rm = TRUE) %>% 
  unite("GadDx", c(M2P1_Anxiety, MRP1_Anxiety,M2KP1_Anxiety, MRKP1_Anxiety), sep = "", na.rm = TRUE) %>%
  unite("Income", c(M2P1_income, MRP1_income, M2KP1_income, MRKP1_income), sep = "", na.rm = TRUE) %>% 
  unite("Race1", c(M2P1_race1, MRP1_race1, M2KP1_race1, MRKP1_race1), sep = "", na.rm = TRUE) %>% 
  unite("Race2", M2P1_race2, MRP1_race2, sep = "", na.rm = TRUE) %>% 
  unite("RaceBest", c(M2P1_racebest, MRP1_racebest, M2KP1_racebest, MRKP1_racebest), sep = "", na.rm = TRUE) %>% 
  unite("Latine", c(M2P1_latine, MRP1_latine, M2KP1_latine, MRKP1_latine), sep = "", na.rm = TRUE) %>% 
  unite("Education", c(M2P1_education, MRP1_education, M2KP1_education, MRKP1_education), sep = "", na.rm = TRUE) %>% 
  unite("PosRelations7", c(M2P1_pos_relations_others7, MRP1_pos_relations_others7, M2KP1_pos_relations_others7, MRKP1_pos_relations_others7), sep = "", na.rm = TRUE) %>% 
  unite("IADLs", c(M2P1_IADL, MRP1_IADL, M2KP1_IADL, MRKP1_IADL), sep = "", na.rm = TRUE) %>% 
  unite("BasicADL2", M2P1_BasicADL2, MRP1_BasicADL2, sep = "", na.rm = TRUE) %>% 
  unite("BasicADL3", c(M2P1_BasicADL3, MRP1_BasicADL3, M2KP1_BasicADL3, MRKP1_BasicADL3), sep = "", na.rm = TRUE) %>% 
  unite("ChildhoodFinances", c(M1P1_childhoodfinances, MRP1_childhoodfinances, MRKP1_childhoodfinances), sep = "", na.rm = TRUE) %>% 
  unite("Welfare", c(M1P1_childhoodwelfare, MRP1_childhoodwelfare, MRKP1_childhoodwelfare), sep = "", na.rm = TRUE) %>% 
  unite("BMI", M2P4_BMI, MRP4_BMI, sep = "", na.rm = TRUE) %>% 
  unite("ChronicConditions", M2P4_TotalChronicConditions, MRP4_TotalChronicConditions, sep = "", na.rm = TRUE) %>% 
  unite("DeathStatus", c(DECEASED.x, DECEASED.y), sep = "", na.rm = TRUE) 

cleanfulldataset <- cleanfulldataset %>% 
  dplyr::select(-M2P1_pos_relations_others3, -A1SPWBR, -B1PAGE_M2) 

```

```{r make summary scores and add vars, eval = TRUE, include = FALSE}
# for Sample column, a value of 1 indicates that it came from M2 (MIDUS core) sample and a value of 2 indicates it came from Refresher sample 

cleanfulldataset <- cleanfulldataset %>% 
mutate(Sample = ifelse(!is.nan(M2ID), "1", "2"))

#remove other columns 
cleanfulldataset <- cleanfulldataset %>% 
dplyr::select(-M2ID, -MRID) %>% mutate_if(is.character,as.numeric)

#write.csv(cleanfulldataset, "cleanfulldata_02282024.csv")
```

```{r Break up mriID in to col, eval = TRUE, include = FALSE}
#takes separate vector for MRI IDs and prepares it
IDS <- separate(mriIDs, ID, sep = "-", into = c("sub", "MR", "MIDUSID"))
IDS$MIDUSID <- as.numeric(IDS$MIDUSID)
# this vector is all the midus IDs of people who were scanned 
```

```{r impute posrelations and outcomes with full data, eval=FALSE, include=FALSE}
tempimpute <- cleanfulldataset %>% dplyr::select(MIDUSID, PosRelations7, IADLs, BasicADL2, BasicADL3, ChronicConditions, Race1, FirstAge)

imputeData <- mice(tempimpute,m=5,maxit=50,meth='pmm') 

imputeData <- complete(imputeData,1)

#write.csv(imputeData, "cleanfulldata_impute_02282024.csv")

```

```{r combine impute data w cleanfulldataset, eval = TRUE, include = FALSE}
imputeData<- read.csv("PATHNAME_REDACTED")

# make Race Di summary score on imputed data
imputeData$Race1 <- as.numeric(imputeData$Race1)
imputeData$Race_Di<- NA

i = 1

for (i in 1:nrow(imputeData)) {
  if(imputeData$Race1[i] == 1 && !is.na(imputeData$Race1[i])) {
     imputeData$Race_Di[i] <- 1
  }
  
  else if(!is.na(imputeData$Race1[i])){
    imputeData$Race_Di[i] <- 0
  }
}

imputeData %>% dplyr::select(Race1, Race_Di)

tempclean <- cleanfulldataset %>% 
  dplyr::select(-PosRelations7, -IADLs, -BasicADL2, -BasicADL3, -ChronicConditions, -Race1, -FirstAge)
# take away these columns from the original dataset because i'm later adding them back from the imputed sheet that filled in the missing gaps

#this perserves all the demographics data to be real but imputes the other data
#imputeData is cleanfulldata but with imputed data
imputeData <- left_join(tempclean,imputeData, by ="MIDUSID")

imputeDataBrainSubs <- inner_join(IDS, imputeData, by = "MIDUSID")

#write.csv(imputeDataBrainSubs, "imputeddataFullSample_BrainSubs_02092024.csv")
```

```{r final datasets with imputed and nonimputed data, eval = TRUE, include = FALSE}
#dataA is whole dataset with imputed data
dataA <- imputeData

dataB <- inner_join(imputeDataBrainSubs, IDS, by = "MIDUSID")
#201 obs with imputed imaging data

dataC <- inner_join(cleanfulldataset, IDS, by = "MIDUSID")
# this is also 201 but has some NAs for key vars
```

```{r make race Di for data C, eval = TRUE, include=FALSE, echo=FALSE}
# make Race Di summary score on imputed data
dataC$Race1 <- as.numeric(dataC$Race1)
dataC$Race_Di<- NA

i = 1

for (i in 1:nrow(dataC)) {
  if(dataC$Race1[i] == 1 && !is.na(dataC$Race1[i])) {
     dataC$Race_Di[i] <- 1
  }
  
  else if(!is.na(dataC$Race1[i])){
    dataC$Race_Di[i] <- 0
  }
}

dataC %>% dplyr::select(Race1, Race_Di)
```


```{r add in MRI quality, eval=TRUE, include = FALSE}
dataB <- inner_join(dataB, quality, by = "MIDUSID")
dataC <- inner_join(dataC, quality, by = "MIDUSID")
```

```{r add in brainage, eval=TRUE, include = FALSE}
dataB <- inner_join(dataB, brainage, by = "MIDUSID")
dataC <- inner_join(dataC, brainage, by = "MIDUSID")
```

```{r calculate BAG, eval=TRUE, include=FALSE}
#ScanAge and AGE are the same

#ANTs_BA

dataB$ANTs_BAG <- 0
dataB$ANTs_BAG <- (dataB$pyment_BA - dataB$AGE)

dataC$ANTs_BAG <- 0
dataC$ANTs_BAG <- (dataC$pyment_BA - dataC$AGE)

#brainageR

dataB$brainageR_BAG <- 0
dataB$brainageR_BAG <- (dataB$brainageR_BA - dataB$AGE)

dataC$brainageR_BAG <- 0
dataC$brainageR_BAG <- (dataC$brainageR_BA - dataC$AGE)

#pyment_BA

dataB$pyment_BAG <- 0
dataB$pyment_BAG <- (dataB$pyment_BA - dataB$AGE)

dataC$pyment_BAG <- 0
dataC$pyment_BAG <- (dataC$pyment_BA - dataC$AGE)

#ENIGMA_BA

dataB$ENIGMA_BAG <- 0
dataB$ENIGMA_BAG <- (dataB$ENIGMA_BA - dataB$AGE)

dataC$ENIGMA_BAG <- 0
dataC$ENIGMA_BAG <- (dataC$ENIGMA_BA - dataC$AGE)


#Kaufmann_BA

dataB$Kaufmann_BAG <- 0
dataB$Kaufmann_BAG <- (dataB$Kaufmann_BA - dataB$AGE)

dataC$Kaufmann_BAG <- 0
dataC$Kaufmann_BAG <- (dataC$Kaufmann_BA - dataC$AGE)
```

```{r calculate scan lag time, eval=TRUE, include=FALSE}
dataB$ScanLag <- 0 
dataB$ScanLag <- (dataB$AGE-dataB$FirstAge)

dataC$ScanLag <- 0 
dataC$ScanLag <- (dataC$AGE-dataC$FirstAge)
```

```{r Sum ADLs, eval=TRUE, include=FALSE}
dataA$sumADL <- 0 
dataA$sumADL <- (dataA$BasicADL3 + dataA$IADL)

dataB$sumADL <- 0 
dataB$sumADL <- (dataB$BasicADL3 + dataB$IADL)

dataC$sumADL <- 0 
dataC$sumADL <- (dataC$BasicADL3 + dataC$IADL)
```

```{r Sum ADLs, eval=TRUE, include=FALSE}
dataA$sumADL <- 0 
dataA$sumADL <- (dataA$BasicADL3 + dataA$IADL)

dataB$sumADL <- 0 
dataB$sumADL <- (dataB$BasicADL3 + dataB$IADL)

dataC$sumADL <- 0 
dataC$sumADL <- (dataC$BasicADL3 + dataC$IADL)
```

```{r write datasets, eval=FALSE, include = FALSE}
write.csv(dataA, "MIDUS_dataA_02282024.csv")
write.csv(dataB, "MIDUS_dataB_02282024.csv")
write.csv(dataC, "MIDUS_dataC_02282024.csv")
```
